---
deployment:
  tasks:
    - export DEPLOYPATH=/home/paulama1/public_html/buscador_pokemon
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp index.js $DEPLOYPATH